apiVersion: v2
name: supabase
description: The open source stack built ontop of Supabase, based upon Supabase-Community
type: application
version: 0.0.5
icon: https://avatars.githubusercontent.com/u/5571997?s=280&v=4