apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: {{ include "supabase.db.fullname" . }}-backup
spec:
  method: barmanObjectStore
  cluster:
    name: {{ include "supabase.db.fullname" . }}