apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "supabase.db.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  imageName: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.db.image.pullPolicy }}
  postgresUID: 101
  postgresGID: 102
  resources: 
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 1Gi
      cpu: 1
  storage:
    size: 2Gi
    storageClass: {{ .Values.db.storage.storageClassName }}
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
  environment:
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: supabase-secret-jwt
          key: secret
    - name: JWT_EXP
      value: "3600"
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: supabase-secret-db
          key: username
    - name: PGPASS
      valueFrom:
        secretKeyRef:
          name: supabase-secret-db
          key: password
  backup:
    barmanObjectStore:
      destinationPath: s3://kilobase/barman/backup
      s3Credentials:
        accessKeyId:
          name: {{ .Values.secret.s3.secretRef }}
          key: {{ .Values.secret.s3.secretRefKey.keyId | quote }}
        secretAccessKey:
          name: {{ .Values.secret.s3.secretRef }}
          key: {{ .Values.secret.s3.secretRefKey.accessKey | quote }}
      wal:
        compression: gzip
  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true
      encoding: 'UTF8'
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: {{ include "supabase.db.fullname" . }}-init
          key: configmap.sql