name: 'GitHub Issues Comment Action'
description: 'A GitHub Action to create a comment on an issue based on the issue ticket and comment.'
inputs:
  token:
    description: 'GitHub token to authenticate requests.'
    required: true
  issue_number:
    description: 'The number of the issue to comment on.'
    required: true
  comment_body:
    description: 'The body of the comment.'
    required: true
  debug:
    description: 'Enable debug loggin for action.'
    required: false
    default: 'false'

outputs:
  comment_id:
    description: 'The ID of the created comment.'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        npm install
      working-directory: ${{ github.action_path }}

    - name: Create comment
      id: create_comment
      shell: bash
      run: |
        node index.js
      working-directory: ${{ github.action_path }}

    - name: Set output
      shell: bash
      run: |
        echo "comment_id=${{ steps.create_comment.outputs.comment_id }}" >> $GITHUB_ENV

branding:
  icon: 'terminal'
  color: 'blue'
