
[workspace]
resolver = '2'
members = [
	'apps/rust_api_profile',
	'packages/kbve',
	'apps/rust_wasm_embed',
	'packages/erust',
	'packages/holy',
	'packages/jedi',
	'apps/kilobase',
]

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = 'abort'
