
[workspace]
resolver = '2'
members = [
	'packages/kbve',
	'packages/erust',
	'packages/holy',
	'packages/jedi',
	'apps/kbve/kilobase',
	'apps/kbve/rust_kanban',
	'apps/kbve/rust_api_profile',
	'apps/rareicon/rust_rareicon_gameserver',
	'apps/rust_wasm_embed',
	'apps/rust_p16_gameserver',
	'apps/rentearth/rust_godot_towerdefense',
]

[profile.dev]
opt-level = 1

[profile.dev.overrides.kilobase]
panic = 'unwind'

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = 'abort'

[profile.release.overrides.kilobase]
panic = 'unwind'
opt-level = 3
lto = 'fat'
codegen-units = 1
