
[workspace]
resolver = '2'
members = [
	'apps/rust_api_profile',
	'packages/kbve',
	'apps/rust_wasm_embed',
	'packages/erust',
	'packages/holy',
	'packages/jedi',
	'apps/kilobase',
]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = 'abort'

# Overrides for specific packages like `kilobase`
[profile.dev.overrides."kilobase"]
panic = "unwind"

[profile.release.overrides."kilobase"]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1