apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-pies
  namespace: fleet-default  # Place this in the appropriate namespace
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root  # Replace this with a secure password
    elemental:
      install:
        reboot: true
        device: /dev/mmcblk0
        debug: true
      # reset:
      #   enabled: true
      #   debug: true
      #   reset-persistent: true
      #   reset-oem: true
      #   reboot: true
      registration:
        emulate-tpm: true
  machineInventoryLabels:
    element: fire
    manufacturer: "${Product/Vendor}"
    productName: "${Product/Name}"
    serialNumber: "${Product/Serial Number}"
    machineUUID: "${Product/UUID}"
  machineInventoryAnnotations:
    edge: "true"
    cluster-role: "worker"