kanban:
    nameOverride: kanban
    name: kanban-app
    replicaCount: 1
    image:
        repository: kbve/kanban
        tag: 1.03.1
        digest: 'sha256:c002234843480e38de0d9fa6fde5f18a449feea238be757c5afe7cd5bffaecf1'
    service:
        name: kanban
        ports:
            - name: tcp
              protocol: TCP
              port: 3000
              targetPort: 3000
            - name: ws
              protocol: TCP
              port: 8086
              targetPort: 8086
        webscoket:
            enabled: true
        udp:
            enabled: false
    ingress:
        enabled: true
        host: kanban.kbve.com
        paths:
            - path: /
              backend: html
            - path: /ws/
              backend: websocket
    resources:
        requests:
            memory: '1Gi'
            cpu: '500m'
        limits:
            memory: '2Gi'
            cpu: '900m'
