name: 'KBVE API Atlas Action'
description: 'An action to call AI routes, like Groq or Ollama, through KBVE API'
author: 'KBVE'

inputs:
  kbve_api:
    description: 'KBVE API Key'
    required: false

  system:
    description: 'System prompt'
    required: false

  message:
    description: 'Message to send to Atlas'
    required: true

  model:
    description: 'LLM Model'
    default: 'mixtral-8x7b-32768'
    required: false

  token:
    description: 'Github Token'
    required: true
  
  ulid:
    description: 'Prompt key/ulid to reference for tasks.'
    required: false


outputs:
  response:
    description: 'API Response'

runs:
  using: 'node20'
  pre: 'npm install'
  main: 'index.js'

branding:
  icon: 'terminal'
  color: 'blue'
