name: 'Localtunnel Action'
description: 'A GitHub Action to expose a local server to the public internet using localtunnel.'
inputs:
  port:
    description: 'The port to expose.'
    required: true
outputs:
  tunnel_url:
    description: 'The URL of the localtunnel.'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        npm install
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Run Localtunnel
      id: localtunnel
      run: |
        node index.js
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Set output
      shell: bash
      run: |
        echo "tunnel_url=${{ steps.localtunnel.outputs.tunnel_url }}" >> $GITHUB_ENV

branding:
  icon: 'terminal'
  color: 'blue'