version: '3.8'

services:
  colyseus:
    hostname: colyseus
    image: kbve/expresscolyseusdiscord:latest
    container_name: colyseus
    restart: unless-stopped
    environment:
      - VITE_CLIENT_ID=PASTE_OAUTH2_CLIENT_ID_HERE
      - CLIENT_SECRET=PASTE_OAUTH2_CLIENT_SECRET_HERE
    configs:
      - source: lavalink_copy_copy
        target: /opt/kbve/config.yml

    volumes:
      - /opt/kbve/
    
    networks:
      - colyseus

    expose:
      - 3000

configs:
  lavalink_copy_copy:
    external: true

networks:
  colyseus:
    name: colyseus
    driver: overlay
    attachable: true