apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: fire-pies
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
      reset:
        enabled: true
        debug: true
        reset-persistent: true
        reset-oem: true
        reboot: true
  machineInventoryLabels:
    element: fire
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
  machineInventoryAnnotations:
    edge: "true"
    cluster-role: "worker"

---
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: fire-pi-img
  namespace: fleet-local  # Change this to fleet-local (or your desired namespace)
spec:
  type: raw
  baseImage: registry.opensuse.org/isv/rancher/elemental/staging/containers/suse/sl-micro/6.0/baremetal-os-container:latest
  targetPlatform: linux/arm64  # Ensure this is the correct platform for your Raspberry Pi (arm64)
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: fire-pies  # Ensure this matches your MachineRegistration name
    namespace: fleet-local  # Ensure the MachineRegistration is under the correct namespace
