defaultNamespace: armada
helm:
    releases:
        - name: sealed-secrets
          chart: sealed-secrets/sealed-secrets
          repo: https://bitnami-labs.github.io/sealed-secrets
          valuesFiles:
              - shipyard/sealed-secrets-values.yaml
          targets:
              - clusterSelector:
                    matchExpressions:
                        - key: cattle.io/cluster-name
                          operator: In
                          values:
                              - kbve-prime
        - name: redis
          chart: bitnami/redis
          repo: https://charts.bitnami.com/bitnami
          valuesFiles:
              - shipyard/redis-values.yaml
          targets:
              - clusterSelector:
                  matchExpressions:
                    - key: cattle.io/cluster-name
                      operator: In
                      values:
                        - kbve-prime