[package]
name = "jedi"
authors = ["kbve", "h0lybyte"]
version = "0.1.16"
edition = "2024"
license = "MIT"
description = "Jedi is the Juggernaut Electronic Data Interchange package. This library provides a data exchange layer extended through the holy crate."
homepage = "https://kbve.com/application/rust/#jedi"
repository = "https://github.com/KBVE/kbve/tree/main/packages/jedi"
readme = "README.md"
rust-version = "1.85"


[build-dependencies]
tonic-build = "0.12.3"

[dependencies]
dashmap = { version = "6.1.0", features = ["serde", "rayon"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ammonia = "4.0.0"
bitflags = { version = "2.9.0", features = ["serde"] }
thiserror = "2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tower = { version = "0.5.2", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.6.1", features = [
    "add-extension",
    "auth",
    "compression-full",
    "limit",
    "trace",
    "fs",
    "cors"
] }
tokio = { version = "1.43", features = ["full", "rt-multi-thread"] }
tokio-postgres = "0.7.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = { version = "0.8.1", features = ["ws", "macros"] }
axum-extra = { version = "0.10.0", features = [
    "typed-header",
    "protobuf",
    "query",
    "json-deserializer",
    "error-response",
    "cookie",
    "form",
    "file-stream"
]}
bb8 = "0.9.0"
bb8-postgres = "0.9.0"
bb8-redis = "0.21.0"
redis = { version = "0.29.1", features = ["tokio-rustls-comp"] }
prost = { version = "0.13", features = ["prost-derive"] }
papaya = "0.2.1"
tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"
http-body-util = "0.1"
ulid = { version = "1", features = ["serde", "uuid"] }
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
hyper = { version = "1.0", features = ["server", "http1", "http2"] }
hyper-util = { version = "0.1", features = ["tokio", "server-auto", "http1"] }
# Replaceable
crossbeam = "0.8.4"
regex = "1.10.3"
once_cell = "1.21.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
