gameserver:
    nameOverride: rareicon
    name: rareicon-app
    replicaCount: 1
    image:
        repository: kbve/rareicongs
        tag: 1.04.0
        digest: "sha256:fdaca75d1612b517f85a78b5954b26302f17c92e11e4c7e4d100cef57b739c68"
    service:
        name: gameserver
        ports:
            - name: tcp
              protocol: TCP
              port: 3000
              targetPort: 3000
            - name: udp
              protocol: UDP
              port: 8081
              targetPort: 8081
        webscoket:
            enabled: true
        udp:
            enabled: true
    ingress:
        enabled: true
        host: discord.rareicon.com
        paths:
            - path: /
              backend: html
            - path: /ws/
              backend: websocket
    resources: {}
