apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rareicon
  name: sealed-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: rareicon
  name: sealed-secrets-rolebinding-rareicon
subjects:
- kind: ServiceAccount
  name: sealed-secrets
  namespace: armada
roleRef:
  kind: Role
  name: sealed-secrets-role
  apiGroup: rbac.authorization.k8s.io
