apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: discord-secret
    namespace: rareicon
spec:
    encryptedData:
        discord-secret: AgA7Glvcnq8s/cRZHcOjVe4eWESblobhq/KfBHv6ktsWqSBJ2W8hqq0Rht6MZsbGcZ12IqarcKOC4QcEZuJISvSicj4mhSU3GOiRyO4QlWDrPq2bISD50WhwwjNvA73JxwdX+dUIND6eq09d6nSPEEX7ftFzdEzmkbXcJsyCHCNe7xyMPAC9mhmvQvxpbwzw2Lh17K0ceI6xdcFb8xlgqk+kUYTKVBIpWKJWfO7a96mRtmg+He73Ah7oocPhgwaRsdqxDOx43LtSAHrwXtQ37SybjDk1TipX2DLKarfdljX2uhSwy4zWD34MTT5rBn9awJMXA/EbYQixp4c5qmn1ViQWiA0pGgYlDdr9Iho4pxwo7m/A5kynhP2N5GLjNhVeJdSSvinKnoA4L/zrKB3AtwQhJG4vcjgYqUvejGyoZsbVTP12Yh0V4/QT7a8ydVoRVxdbk+j4ZOhf9fi/fUCngHCc4p/bmCXTPybLmdgh7LO3nLApxOVG/OEq2VB6FQjzvAevq+4N4ab2+enU82xqLjpBpXnu4NokpdAdkx5tXRdgCq/CD2b8TMGOofNfVKDSgTEnbjDemmUatCpVieFN6MN4XaEg69AfrVrJyEiInXAPe0CJuxF2LOOfQmW3LcNatPqQMUSudfQ4UHFBpqDc/yJWB/gWEsleXV9YUOAPQNiuUBjHWAH250c/ghb6DMZ4UJRSoUmhUh6zF/rMhq0Jd7s5I4kAAQ==
    template:
        metadata:
            name: discord-secret
            namespace: rareicon

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: DISCORD_CLIENT_SECRET
    namespace: rareicon
spec:
    encryptedData:
        DISCORD_CLIENT_ID: AgA6rqpUIIyUzKLi5nGmH0XyRXmTdObbFZf7d4AK4ow1hI5xX6LrcbzJyuVBTS8A0FuiOSiWXhFyYM98LPL/gtNtElT8kbdY5OduSmlOllPUOQvPGdAOBA4CDZLz4f9OoU7lLAknOYgHFgoE/P1c2cW4VVhbmT7wjT3st8PRvL6z69uIkULomS8dyfStlVHv5Nb4zsZkhoa76MInyV5x+SGR8LRQ4Oiv6ERlalYGgWFcQP7WBKpNNXOkrkIGfKs//2ryPiQcPSs+tE3ebaonWJV3GMZHE72wWdLMd4thufLTykcXADPaUChVPWtqxHsga0vKo0ayEIYqKZ0tcygbY8H67+a47zIVfjYRTrN1Zlv+FfcFeeIrqtsitGtXUWXkObU4j1/1ZujM12c3cIJUClbnLPQsKIR1lxFz+zRBSYn3J+D7m4Vv+mZUtRmsfJ3T7uDQc/Bng3kEnxZjZJyXgd1AbZAqWKMYK0SIvzl1N3J+86Wlzd8kLUDzDatzpzaaH5cKpR63/1eU009X6f24G30YNbTScr2yJnBBHnDER+4nJ0D2RVBK++KAn4/SaVJsAzCRKh5zdib1q1JfVYuB/+JtmKqdVBEz2NU0VpMSHLLew7pWm1qo5xmOvmHKAiZDS6JsMnjidvofgoKkaBFg2WNKT4w+jIxq0qOSxz+/8UxXGSBgmfyeQdNT7E8svzBiaExiusVIw3ZDi/eAuiJ3ZhQXPJcR
        DISCORD_CLIENT_SECRET: AgC22fFZf8swxbV3hRuYOvZvVSlapDgLze60/t5CDpLlpQewrZkuqUdZiHMSs+7VxkdanRyoSivty3MqBkDbFH3H87aCXdwLC05meNPzMkmyZvW0A1VFMCuv/aNuZrTHpQ95eoNSe+ICv7/dFZNAdaWLpFztXrNyvCJq5pFJ0XVR98yD1vKFL6Zl8JlNiOLYcr+Q1ZiFTL46ckL7Yh6Z7qC0+UT+ynlvHiWp5Ph1jmn5MyxeiDsZURjq8PJFFXdUxTVD30KitfyvRnCHtp0gt3uu2ok2viWkENnKn1VHL8DW6eLI5NK3L5qWCXoqR7g1UUN4kNrpWJWFCzEAocjyuJ/j7l8e04uw1f+oZqhiLDD/DmbtpUgnf3i9sPiB0NLLrxKKmvmnzvLubQg4bCx3BJTnuIKKkf3BxUeUK42KmYCViFE8hYrCiOvjupvmAIuS78hiKomAQadt5Ks/A/QET5BErTCKirYDLqmHDDk6zkYx7KGTBe8R51bMz+X2/5n0+f1oH4HajZpNsEdDgIbLZ0oRZng2bUbPkeV5w/l385px2ETSxGHUCtt+IJiIh4rY8cGMVlXwyQOcksHjiFMm35Bt2XLsVZOHs9XYKIjrdDVw6M0UH3CqAty5k+jy1IoD6jf+C4u3FLj+c/4EKXMVQTQpzmz94zMiqaG+mj8sC8E/xN3NUNso0XJIJe12wUlyRz03Bp4PmSR8DxfgU+4am5OlUGoI1LMcr1hjZWb+n5Zc0g==
    template:
        metadata:
            name: DISCORD_CLIENT_SECRET
            namespace: rareicon
