sealed-secrets:
    fullnameOverride: sealed-secrets
    replicaCount: 3
    secretName: sealed-secrets-key
    clusterWide:
        enabled: false
    keyManagementService:
        use: false
    customResourceDefinitions:
        create: true
    serviceAccount:
        create: true
    tls:
        enabled: true
    securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
    keyRenewPeriod: '30d'
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 50m
            memory: 64Mi

redis:
    fullnameOverride: redis
    architecture: standalone
    auth:
        enabled: true
        existingSecret: redis-auth
        passwordKey: redis-password
    replica:
        replicaCount: 1
    metrics:
        enabled: true
        extraArgs:
            redis.password: '$(REDIS_PASSWORD)'
            # redis.addr: redis-master:6379
        env:
            - name: REDIS_PASSWORD
              valueFrom:
                  secretKeyRef:
                      name: redis-auth
                      key: redis-password
        serviceMonitor:
            enabled: true
            namespace: armada
            # additionalLabels:
            #     app.kubernetes.io/name: redis
            #     app.kubernetes.io/component: metrics
            #     app.kubernetes.io/instance: armada-release

# hami:
#     scheduler:
#         kubeScheduler:
#             imageTag: v1.30.4 # Use the Kubernetes server version as the image tag

#     
#     vgpuDevicePlugin:
#         image:
#             repository: hami/vgpu-device-plugin
#             tag: 2.4.0

#     vgpuScheduler:
#         image:
#             repository: hami/vgpu-scheduler
#             tag: 2.4.0
