sealed-secrets:
    fullnameOverride: sealed-secrets
    replicaCount: 3
    secretName: sealed-secrets-key
    clusterWide:
        enabled: false
    keyManagementService:
        use: false
    customResourceDefinitions:
        create: true
    serviceAccount:
        create: true
    tls:
        enabled: true
    securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
    keyRenewPeriod: '30d'
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 50m
            memory: 64Mi

redis:
    fullnameOverride: redis
    architecture: standalone
    auth:
        enabled: true
        existingSecret: redis-auth
        passwordKey: redis-password
    replica:
        replicaCount: 1
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
            namespace: cattle-monitoring-system
    redisLegendInput: 'Redis Input'
    redisLegendOutput: 'Redis Output'
