name: 'Github Issue Ticket Title Parser'
description: 'Parse the Github issue ticket title based upon the inputs and returns a boolean'
author: 'KBVE'

inputs:
  title:
    description: 'Title to parse'
    required: true
  keyword:
    description: 'Array of objects with keyword and action'
    required: true
  debug:
    description: 'Enable debug logging for action.'
    required: false
    default: 'false'


outputs:
  action:
    description: 'Matched action'


runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        npm install
      working-directory: ${{ github.action_path }}

    - name: Set environment variables
      shell: bash
      run: |
        echo "TITLE=${{ inputs.title }}" >> $GITHUB_ENV
        echo "KEYWORD=${{ inputs.keyword }}" >> $GITHUB_ENV
        echo "DEBUG=${{ inputs.debug }}" >> $GITHUB_ENV

    - name: Parse comment
      id: parse_action
      shell: bash
      run: |
        node index.js
      working-directory: ${{ github.action_path }}

    - name: Set output
      shell: bash
      run: |
        echo "action=${{ steps.parse_action.outputs.action }}" >> $GITHUB_ENV

branding:
  icon: 'terminal'
  color: 'blue'