name: CI Patch

# Docs for this Github workflow is here https://kbve.com/application/git/#ci-patch.yml

on:
  push:
    branches:
      - 'patch*'

  pull_request:
    types: [synchronize]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch dev branch
        run: git fetch origin dev


      - name: Get Commits
        id: get_commits
        run: |
            commits=$(git log --oneline origin/dev..HEAD | tr '\n' '|')
            echo "commits=$commits" >> $GITHUB_OUTPUT
      - name: Auto-Pull
        uses: diillson/auto-pull-request@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: 'dev'
          pr_title: 'Pulling ${{ github.ref }} into Dev'
          pr_body: |
            *An automated PR*

            Commits:
            ${{ steps.get_commits.outputs.commits }}
          pr_label: 'auto-pr'
