name: CI Patch

on:
  push:
    branches:
      - 'patch*'
  pull_request:
    branches:
      - 'dev'
    types: [synchronize]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Get Commits
        id: get_commits
        run: |
          commits=$(git log --oneline origin/dev..HEAD | tr '\n' '|')
          echo "commits=$commits" >> $GITHUB_OUTPUT

  create_pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto-Pull
        uses: diillson/auto-pull-request@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: 'dev'
          pr_title: 'Pulling ${{ github.ref }} into Dev'
          pr_body: |
            *An automated PR*

            Commits:
            ${{ steps.get_commits.outputs.commits }}
          pr_label: 'auto-pr'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @kbve/devops

      - name: Call Process and Update PR Function
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { _$gha_processAndUpdatePR } = require('@kbve/devops');
            const branchToCompare = 'dev'; // You can replace this with a variable or dynamic value if needed
            await _$gha_processAndUpdatePR(branchToCompare, github, context);

  update_pr:
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install @kbve/devops --legacy-peer-deps

      - name: Call Process and Update PR Function
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { _$gha_processAndUpdatePR } = require('@kbve/devops');
            const branchToCompare = 'dev'; // You can replace this with a variable or dynamic value if needed
            await _$gha_processAndUpdatePR(branchToCompare, github, context);
