name: Process Atlas Commands

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

env:
  atlas_action: none

jobs:
  process_issue:
    name: 'Process Issue'
    runs-on: ubuntu-latest

    outputs:
      matched_action: ${{ steps.title-parser.outputs.action }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Parse Issue Title
        id: title-parser
        uses: ./.github/actions/github-i-title-parse
        with:
          title: ${{ github.event.issue.title }}
          keywords: '[{"keyword": "Atlas", "action": "atlas_action"}, {"keyword": "Music", "action": "music_action"}]'

      - name: Set matched_action environment variable
        run: echo "matched_action=${{ steps.title-parser.outputs.action }}" >> $GITHUB_ENV

  handle_atlas:
    name: 'Handle Atlas Ticket'
    runs-on: ubuntu-latest
    needs: ['process_issue']
    if: needs.process_issue.outputs.matched_action == 'atlas_action'
    steps:
      - name: Comment on issue!
        id: comment_id
        uses: ./.github/actions/github-i-comment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          comment_body: |
            Preparing to launch the shuttle.
