name: Process Atlas Commands

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

env:
  atlas_action: none

jobs:
  process_issue:
    name: 'Process Issue'
    runs-on: ubuntu-latest

    outputs:
      matched_action: ${{ steps.title-parser.outputs.action }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: | 
          npm install @kbve/devops

      - name: Check title of the ticket
        id: title-parser
        uses: actions/github-script@v7
        with:
          script: |
            const { _$gha_kbve_ActionProcess } = require('@kbve/devops');
            const title = context.payload.issue.title;
            const action = _$gha_kbve_ActionProcess(title);
            core.setOutput('action', action);

      - name: Debug matched action
        run: |
          echo "Matched action is: ${{ steps.title-parser.outputs.action }}"


  handle_atlas:
    name: 'Handle Atlas Ticket'
    runs-on: ubuntu-latest
    needs: ['process_issue']
    if: needs.process_issue.outputs.matched_action == 'atlas_action'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: | 
          npm install @kbve/devops

      - name: Atlas Debug Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |

            const issue_number = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const body = 'This is a comment added by the GitHub Action.';
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: body
              });
