name: Auto Approve

on: 
    pull_request_target:
        branches:
            - dev

jobs:
    auto-approve:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        if: github.actor == 'h0lybyte' && github.event.pull_request.base.ref == 'dev' && contains(github.event.pull_request.head.ref, 'patch-atomic-')
        steps:
            -   uses: hmarr/auto-approve-action@v3
                with:
                    review-message: "Auto approved automated PR"