name: Process Music Issues

on:
  issues:
    types: [opened]

permissions:
  issues: read
  contents: read

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if issue title contains [MUSIC]
      id: check_title
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        echo "Issue Title: $ISSUE_TITLE"
        if echo "$ISSUE_TITLE" | grep -q "\[MUSIC\]"; then
          echo "is_music_issue=true" >> $GITHUB_ENV
        else
          echo "is_music_issue=false" >> $GITHUB_ENV
        fi

    - name: Stop if not a music issue
      if: env.is_music_issue == 'false'
      run: echo "Not a music issue. Skipping further steps."

    - name: Check for YouTube link in issue body
      if: env.is_music_issue == 'true'
      id: check_youtube
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
      run: |
        echo "Issue Body: $ISSUE_BODY"
        if echo "$ISSUE_BODY" | grep -q "https://www.youtube.com/watch?v="; then
          YOUTUBE_ID=$(echo "$ISSUE_BODY" | grep -oP 'https://www.youtube.com/watch\?v=\K[\w-]+')
          echo "has_youtube_link=true" >> $GITHUB_ENV
          echo "youtube_id=$YOUTUBE_ID" >> $GITHUB_ENV
        else
          echo "has_youtube_link=false" >> $GITHUB_ENV
        fi

    - name: Display YouTube link check result
      if: env.is_music_issue == 'true'
      run: |
        echo "Contains YouTube link: ${{ env.has_youtube_link }}"

    - name: Extract and display YouTube ID if link is found
      if: env.has_youtube_link == 'true' && env.is_music_issue == 'true'
      run: |
        echo "YouTube ID: ${{ env.youtube_id }}"
