name: Process Media Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  process_issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'media' || contains(github.event.issue.labels.*.name, 'media')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get issue contents
      id: get_issue
      uses: actions/github-script@v7
      with:
        script: |
          const issue_number = context.payload.issue.number;
          const issue = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number
          });
          return issue.data.body;

    - name: Check for YouTube link
      id: check_youtube
      uses: actions/github-script@v7
      with:
        script: |
          const issue_body = `{{ steps.get_issue.outputs.result }}`;
          const youtube_regex = /https?:\/\/(www\.)?youtube\.com\/watch\?v=[\w-]+/gi;
          const has_youtube_link = youtube_regex.test(issue_body);
          return { has_youtube_link: has_youtube_link };
        result-encoding: json

    - name: Display issue contents
      run: |
        echo "Issue body: ${{ steps.get_issue.outputs.result }}"
    
    - name: Display YouTube link check result
      run: |
        echo "Contains YouTube link: ${{ steps.check_youtube.outputs.has_youtube_link }}"
