name: File Alterations

on:
  workflow_call:
    inputs:
        branch:
          description: "Branch to check out"
          required: false
          type: string
          default: "main"

    outputs:
      atlas:
        description: "Atlas changed"
        value: ${{ jobs.alter.outputs.atlas }}
      discordsh_website:
        description: "Discord.sh changed"
        value: ${{ jobs.alter.outputs.discordsh_website }}
      herbmail:
        description: "Herbmail changed"
        value: ${{ jobs.alter.outputs.herbmail }}
      kbve:
        description: "KBVE changed"
        value: ${{ jobs.alter.outputs.kbve }}
      rareicon:
        description: "Rareicon changed"
        value: ${{ jobs.alter.outputs.rareicon }}
      proxy:
        description: "Proxy changed"
        value: ${{ jobs.alter.outputs.proxy }}
      saber:
        description: "Saber changed"
        value: ${{ jobs.alter.outputs.saber }}
      rust_profile:
        description: "Rust profile changed"
        value: ${{ jobs.alter.outputs.rust_profile }}
      cryptothrone:
        description: "CryptoThrone changed"
        value: ${{ jobs.alter.outputs.cryptothrone }}
      erust:
        description: "Erust package changed"
        value: ${{ jobs.alter.outputs.erust }}
      holy:
        description: "Holy package changed"
        value: ${{ jobs.alter.outputs.holy }}
      kbve_crate:
        description: "KBVE Crate package changed"
        value: ${{ jobs.alter.outputs.kbve_crate }}
      jedi:
        description: "Jedi package changed"
        value: ${{ jobs.alter.outputs.jedi }}
      docker_void:
        description: "Dockervoid changed"
        value: ${{ jobs.alter.outputs.docker_void }}
      khashvault:
        description: "Khashvault changed"
        value: ${{ jobs.alter.outputs.khashvault }}
      devops:
        description: "DevOps changed"
        value: ${{ jobs.alter.outputs.devops }}
      fudster:
        description: "Fudster changed"
        value: ${{ jobs.alter.outputs.fudster }}
      laser:
        description: "Laser package changed"
        value: ${{ jobs.alter.outputs.laser }}
      worker:
        description: "Worker changed"
        value: ${{ jobs.alter.outputs.worker }}
      q:
        description: "Q package changed"
        value: ${{ jobs.alter.outputs.q }}
      asteroids:
        description: "Asteroids & Droids changed"
        value: ${{ jobs.alter.outputs.asteroids }}
      kilobase:
        description: "Kilobase package changed"
        value: ${{ jobs.alter.outputs.kilobase }}

jobs:
  alter:
    runs-on: ubuntu-latest
    name: File Alterations
    outputs:
      herbmail: ${{ steps.delta.outputs.herbmail_any_changed }}
      kbve: ${{ steps.delta.outputs.kbve_all_changed_files }}
      rareicon: ${{ steps.delta.outputs.rareicon_all_changed_files }}
      discordsh: ${{ steps.delta.outputs.discordsh_all_changed_files }}
      atlas: ${{ steps.delta.outputs.atlas_any_changed }}
      proxy: ${{ steps.delta.outputs.proxy_any_changed }}
      saber: ${{ steps.delta.outputs.saber_any_changed }}
      rust_profile: ${{ steps.delta.outputs.rust_profile_any_changed }}
      cryptothrone: ${{ steps.delta.outputs.cryptothrone_any_changed }}
      erust: ${{ steps.delta.outputs.erust_any_changed }}
      holy: ${{ steps.delta.outputs.holy_any_changed }}
      kbve_crate: ${{ steps.delta.outputs.kbve_crate_any_changed }}
      jedi: ${{ steps.delta.outputs.jedi_any_changed }}
      docker_void: ${{ steps.delta.outputs.docker_void_any_changed }}
      khashvault: ${{ steps.delta.outputs.khashvault_any_changed }}
      devops: ${{ steps.delta.outputs.devops_any_changed }}
      fudster: ${{ steps.delta.outputs.fudster_any_changed }}
      laser: ${{ steps.delta.outputs.laser_any_changed }}
      worker: ${{ steps.delta.outputs.worker_any_changed }}
      q: ${{ steps.delta.outputs.q_any_changed }}
      asteroids: ${{ steps.delta.outputs.asteroids_any_changed }}
      kilobase: ${{ steps.delta.outputs.kilobase_any_changed }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: File Changes
        id: delta
        uses: step-security/changed-files@v45
        with:
          files_yaml: |
            herbmail:
                - 'apps/herbmail/README.md'
            kbve:
                - 'apps/kbve/kbve.com/**'
            rareicon:
                - 'apps/rareicon/rareicon.com/**'
            discordsh:
                - 'apps/discord.sh/**'
            atlas:
                - 'apps/atlas/kbve_atlas/**'
            proxy:
                - 'apps/proxy/**'
            saber:
                - 'apps/saber/**'
            rustprofile:
                - 'apps/rust_api_profile/**'
            erust:
                - 'packages/erust/src/**'
            holy:
                - 'packages/holy/src/**'
            kbvecrate:
                - 'packages/kbve/src/**'
            jedi:
                - 'packages/jedi/src/**'
            expolcagents:
                - 'apps/expo-lcagents/src/**'
            dockervoid:
                - 'migrations/docker/v01d/**'
            khashvault:
                - 'packages/khashvault/package.json'
            devops:
                - 'packages/devops/package.json'
            fudster:
                - 'apps/fudster/fudster/**'
            cryptothrone:
                - 'apps/cryptothrone.com/src/**'
            laser:
                - 'packages/laser/package.json'
            q:
                - 'packages/rust/q/README.md'
            asteroids:
                - 'apps/gamejam/brackeys/13/**'
            kilobase:
                -  'apps/kbve/kilobase/README.md'
