apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: redis-armada-monitor
    namespace: cattle-monitoring-system
    labels:
        release: prometheus-operator
spec:
    selector:
        matchLabels:
            app.kubernetes.io/name: redis
    endpoints:
        - port: http-metrics
          interval: 30s
    namespaceSelector:
        matchNames:
            - armada
    relabel_configs:
        - source_labels:
              - __meta_kubernetes_service_label_app_kubernetes_io_component
              - __meta_kubernetes_service_labelpresent_app_kubernetes_io_component
          separator: ;
          regex: (master|metrics);true
          replacement: $1
          action: keep
