---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-service-monitor
  namespace: armada

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-scrape
  namespace: armada
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-scrape-binding
  namespace: armada
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-scrape
subjects:
  - kind: ServiceAccount
    name: redis-service-monitor
    namespace: armada

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: redis-armada-monitor
    namespace: cattle-monitoring-system
    labels:
        release: prometheus-operator
spec:
    selector:
        matchLabels:
            app.kubernetes.io/name: redis
            app.kubernetes.io/component: metrics
    endpoints:
        - port: http-metrics
          interval: 30s
          path: /metrics
    namespaceSelector:
        matchNames:
            - armada
