[package]
name = "rust_soul"
authors = ["kbve", "h0lybyte"]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Soul is a utility library for Solana, designed to accelerate proof-of-concept development."
homepage = "https://kbve.com/application/rust/"
repository = "https://github.com/KBVE/kbve/tree/main/packages/erust"
readme = "README.md"
rust-version = "1.85"
exclude = [
    "release/*",
    "docs/*",
]

#[lib]
#crate-type = ["cdylib"]

[dependencies]
solana-client = "2.2.2"
solana-sdk = "2.2.1"
solana-program = "2.2.1"
papaya = "0.1.8"
borsh = "1.5.5"
borsh-derive = "1.5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = { version = "2.9.0", features = ["serde"] }
tokio = { version = "1.43", features = ["full", "rt-multi-thread"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
axum = "0.8.1"
